@domain=http://localhost:3000

### list data
GET {{domain}}/dados
### create data
POST {{domain}}/dados
Content-Type: application/json

{
    "nome": "Nome Teste",
    "endereço": "Endereço Teste",
    "telefone": "Tel Teste",
    "anos": "Anos Teste",
    "horários": "Horários Teste",
    "mapa": "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3958.9172794194133!2d-34.876050590883295!3d-7.135564292838718!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x7ace810852ae4f1%3A0xaf5445223401f2bb!2sIFPB%20-%20Campus%20Jo%C3%A3o%20Pessoa!5e0!3m2!1spt-BR!2sbr!4v1711325830441!5m2!1spt-BR!2sbr",
    "foto": "IFPB - CAMPUS JOÃO PESSOA.png"
}